import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button } from "antd";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Button type="primary">Primary Button</Button>
          <h1>Hello next level developer.</h1>
          <Button type="text">
            <Link href="/news">News</Link>
          </Button>
        </div>
      </main>
    </>
  );
}
